name: Build and test

on:
  push:
jobs:
  build:
    runs-on: ubuntu:lastest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.PRIVATE_REGISTRY_USERNAME }}
          password: ${{ secrets.PRIVATE_REGISTRY_TOKEN }}
      - name: Build and push spark_base
        uses: docker/build-push-action@v6
        with:
          context: "."
          file: base.Dockerfile
          platforms: linux/amd64
          push: true
          tags: zizdlp/spark_base
